sudo: false
dist: trusty

env:
  - PROTOBUF_VERSION=3.1.0

language: rust

matrix:
  include:
  - name: Stable
    rust: stable
  - name: Beta
    rust: beta
  - name: Nightly
    rust: nightly

script:
  - ci/run.sh

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
