sudo: false

#env:
#  - PROTOBUF_VERSION=2.6.1
#  - PROTOBUF_VERSION=3.0.0-beta-2

language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - rustc --version
  - ./cargo.sh build
  - ./test.sh
  - ./build-all.sh

notifications:
  email:
    on_success: never
