sudo: false

#env:
#  - PROTOBUF_VERSION=2.6.1
#  - PROTOBUF_VERSION=3.0.0-beta-2

language: rust

rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler

script:
  - rustc --version
  - ./test.sh
  - ./gen-rs.sh
  - ./build-all.sh

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
