[package]

name = "grpc"
version = "0.0.2"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Rust implementation of gRPC"
repository = "https://github.com/stepancheg/grpc-rust"
readme = "README.md"
keywords = ["grpc"]

[dependencies]
solicit     = { git = "http://github.com/mlalic/solicit.git" }
#protobuf   = { path = "../rust-protobuf" }
protobuf    = { git = "http://github.com/stepancheg/rust-protobuf" }
futures     = { git = "https://github.com/alexcrichton/futures-rs" }
futures-io =  { git = "https://github.com/alexcrichton/futures-rs" }
futures-mio = { git = "https://github.com/alexcrichton/futures-rs" }

[[bin]]

name = "protoc-gen-rust-grpc"
test = false

[workspace]
members = [
    "grpc-examples",
]
