[package]

name = "grpc"
version = "0.0.1"

[dependencies.solicit]
git = "http://github.com/mlalic/solicit.git"

[dependencies.protobuf]
#git = "http://github.com/stepancheg/rust-protobuf"
path = "../rust-protobuf"

[[bin]]

name = "protoc-gen-rust-grpc"
test = false

[[bin]]

name = "temp-server"
test = false

[workspace]
members = [
    "route-guide",
]
