[package]

name = "grpc"
version = "0.2.1"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Rust implementation of gRPC"
repository = "https://github.com/stepancheg/grpc-rust"
readme = "../README.md"
keywords = ["grpc"]

[dependencies]
log             = "0.4"
protobuf        = { version = "1.*", features = ["with-bytes"] }
futures         = "0.1"
futures-cpupool = "0.1"
tokio-core      = "0.*"
tokio-io        = "0.*"
tokio-tls-api   = "0.*"
httpbis         = "=0.4.3"
tls-api         = "0.*"
tls-api-stub    = "0.*"
bytes           = "0.4"
base64          = "0.9"

[lib]
doctest = false
