[package]
name = "test-protoc-plugin"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
publish = false

[dependencies]
tls-api         = "0.1.*"
protobuf        = { version = ">=2.8.0, <2.10.0" }
grpc            = { path = "../../grpc" }
futures-cpupool = "0.1.*"

[lib]
test = false
doctest = false

[workspace]
