[package]
name = "grpc-examples"
version = "0.1.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]

[lib]
doctest = false

[dependencies.grpc]
path = ".."

[dependencies]
protobuf        = { git = "http://github.com/stepancheg/rust-protobuf" }
futures         = { git = "https://github.com/alexcrichton/futures-rs" }
futures-cpupool = { git = "https://github.com/alexcrichton/futures-rs" }
