[package]
name = "grpc-examples"
version = "0.1.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]

[dependencies.grpc]
path = ".."

[dependencies]
protobuf    = { path = "../../rust-protobuf" }
futures     = { git = "https://github.com/alexcrichton/futures-rs" }
